<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
* CourseRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class CourseRepository extends EntityRepository
{
  public function getCoursesOrderedById() {
    return $this->createQueryBuilder('c')
    ->orderBy('c.school')
    ->getQuery()
    ->getResult();
  }

  public function getCoursesById($ids) {
    $qb = $this->createQueryBuilder('c');
    $qb->where($qb->expr()->in('c.id', $ids));
    return $qb->getQuery()->getResult();
  }

  public function getCourseById($id){
    return $this->createQueryBuilder('c')
    ->where('c.id =: id')
    ->setParameter('id',$id)
    ->getQuery()
    ->getResult();
  }
}
