<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * courseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{

    public function getCourse(){

    }

    public function getCourseById($id){
        return $this->createQueryBuilder('c')
            ->addSelect('engid');

    }
}
