<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * courseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
    public function getCourseOrderedById() {
        return $this->createQueryBuilder('c')
            ->orderBy('c.id')
            ->getQuery()
            ->getResult();
    }
    
    public function getCourseById($id){
        return $this->createQueryBuilder('c')
            ->where('c.id =: id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}
