<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
      public function getNotificationOrderedById() {
        return $this->createQueryBuilder('n')
                        ->orderBy('n.id')
                        ->getQuery()
                        ->getResult();
      }
      public function getLastNotificationOrderedByDate(){
        return $this->createQueryBuilder('n')
                    ->setMaxResults(3)
                    ->orderBy('n.notificationDate', 'DESC')
                    ->getQuery()
                    ->getResult();
      }
}
