<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTypeRepository extends EntityRepository {

    public function getNotificationTypesOrderedById() {
        return $this->createQueryBuilder('nt')
                        ->orderBy('nt.id')
                        ->getQuery()
                        ->getResult();
    }

    public function getNotificationTypesById($ids) {
        $qb = $this->createQueryBuilder('nt');
        $qb->where($qb->expr()->in('nt.id', $ids));
        return $qb->getQuery()->getResult();
    }

    public function getNotificationTypeById($id) {
        return $this->createQueryBuilder('nt')
                        ->where('nt.id =:id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getSingleResult();
    }

}
