<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * promoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promoRepository extends EntityRepository
{
    public function getPromoOrderedById() {
        return $this->createQueryBuilder('p')
            ->orderBy('p.id')
            ->getQuery()
            ->getResult();
    }

    public function getPromoById($id){
        return $this->createQueryBuilder('p')
            ->where('p.id =: id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}
