<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * schoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    public function getSchoolsOrderedById() {
        return $this->createQueryBuilder('s')
            ->orderBy('s.id')
            ->getQuery()
            ->getResult();
    }
    public function getSchoolsById($ids) {
      $qb = $this->createQueryBuilder('s');
      $qb->where($qb->expr()->in('s.id', $ids));
      return $qb->getQuery()->getResult();
    }

    public function getSchoolById($id){
        return $this->createQueryBuilder('s')
            ->where('s.id =: id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getResult();
    }
}
