<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{
    public function getSkillOrderedById() {
        return $this->createQueryBuilder('s')
                        ->orderBy('s.id')
                        ->getQuery()
                        ->getResult();
      }
}
