<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
    public function getStatesOrderedById() {
        return $this->createQueryBuilder('s')
                        ->orderBy('s.id')
                        ->getQuery()
                        ->getResult();
    }

    public function getStateById($id) {
        return $this->createQueryBuilder('s')
                        ->where('s.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getSingleResult();
    }
}
