<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function getUsersOrderedById(){
    return $this->createQueryBuilder('u')
                ->orderBy('u.id')
                ->getQuery()
                ->getResult();
  }

  public function getUserById($id) {
      return $qb = $this->createQueryBuilder('u')
                      ->where('u.id = :id')
                      ->setParameter('id', $id)
                      ->getQuery()
                      ->getSingleResult();
  }
}
