<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSkillRepository extends EntityRepository
{
    public function getUserSkillById($id) {
        return $qb = $this->createQueryBuilder('us')
                ->where('us.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleResult();
    }
    public function getUsersBySkill($skill) {
        return $this->createQueryBuilder('s')
                        ->where('s.skill LIKE :skill')
                        ->setParameter('skill', 1)
                        ->getQuery()
                        ->getResult();
    }
}
