   
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Imie\SkillsBundle\Entity\User : plaintext

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:

        main:
            entity: { class: Imie\SkillsBundle\Entity\User, property: userLastName}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: true
            provider: main
            form_login: 
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

        main:
            anonymous: ~
        
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }