imie_skills_home:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Home:index }

imie_skills_user_my_profile:
    path:     /user/{id}
    defaults: { _controller: ImieSkillsBundle:User:myProfile }

imie_skills_user_add_profile:
    path:     /user/
    defaults: { _controller: ImieSkillsBundle:User:addProfile }

imie_skills_project_my_projects:
    path:     /project/{id}
    defaults: { _controller: ImieSkillsBundle:Project:myProjects }

imie_skills_project_add_project:
    path:     /project/
    defaults: { _controller: ImieSkillsBundle:Project:addProject }

imie_skills_project_index:
    path:     /projects
    defaults: { _controller: ImieSkillsBundle:Project:index }

imie_skills_contact:
    path:     /contact
    defaults: { _controller: ImieSkillsBundle:Contact:index }

imie_skills_search:
    path:     /search
    defaults: { _controller: ImieSkillsBundle:Search:newSearch }
