imie_skills_home:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Home:index }

imie_skills_homepage:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Homepage:index }

imie_skills_user_me:
    path:     /user/{id}
    defaults: { _controller: ImieSkillsBundle:User:me }
    requirements:
      id: \d+

imie_skills_user_add:
    path:     /user/add
    defaults: { _controller: ImieSkillsBundle:User:add }

imie_skills_skill_add:
    path:     /skill/add
    defaults: { _controller: ImieSkillsBundle:Skill:add }

imie_skills_project_index:
    path:     /projects
    defaults: { _controller: ImieSkillsBundle:Project:index }

imie_skills_project_details:
    path:     /project/{id}
    defaults: { _controller: ImieSkillsBundle:Project:details }
    requirements:
      id: \d+

imie_skills_project_add:
    path:     /project/add
    defaults: { _controller: ImieSkillsBundle:Project:add }

imie_skills_notification_index:
    path:   /notification
    defaults: {_controller: ImieSkillsBundle:Notification:index}

imie_skills_notification_details:
    path:   /notification/details
    defaults: {_controller: ImieSkillsBundle:Notification:details}

imie_skills_notification_add:
    path:   /notification/add
    defaults: {_controller: ImieSkillsBundle:Notification:add}

imie_skills_notification_delete:
    path:    /notification/delete
    defaults : {_controller: ImieSkillsBundle:Notification:delete}

imie_skills_contact:
    path:     /contact
    defaults: { _controller: ImieSkillsBundle:Contact:index }

imie_skills_search:
    path:     /search
    defaults: { _controller: ImieSkillsBundle:Search:newSearch }
