imie_skills_home:
    path:    /
    defaults: { _controller: ImieSkillsBundle:Home:index }


# -------- SCHOOL --------

imie_skills_school_index:
    path:    /school/index
    defaults : {_controller: ImieSkillsBundle:School:index }

imie_skills_school_add:
    path:    /school/add
    defaults : {_controller: ImieSkillsBundle:School:add }

imie_skills_school_delete:
    path:    /school/delete
    defaults : {_controller: ImieSkillsBundle:School:delete }


# -------- COURSE --------

imie_skills_course_index:
    path:    /course/index
    defaults : {_controller: ImieSkillsBundle:Course:index }

imie_skills_course_add:
    path:    /course/add
    defaults : {_controller: ImieSkillsBundle:Course:add }

imie_skills_course_delete:
    path:    /course/delete
    defaults : {_controller: ImieSkillsBundle:Course:delete }


# -------- PROMO --------

imie_skills_promo_index:
    path:    /promo/index
    defaults : {_controller: ImieSkillsBundle:Promo:index }

imie_skills_promo_add:
    path:    /promo/add
    defaults : {_controller: ImieSkillsBundle:Promo:add }

imie_skills_promo_delete:
    path:    /promo/delete
    defaults : {_controller: ImieSkillsBundle:Promo:delete }


# -------- PROJECT --------

imie_skills_project_index:
    path:    /project/index
    defaults: { _controller: ImieSkillsBundle:Project:index }

imie_skills_project_details:
    path:    /project/{id}
    defaults: { _controller: ImieSkillsBundle:Project:details }
    requirements:
        id: \d+

imie_skills_project_add:
    path:    /project/add
    defaults: { _controller: ImieSkillsBundle:Project:add }

imie_skills_project_modify:
    path:    /project/modify/{id}
    defaults: { _controller: ImieSkillsBundle:Project:modify }
    requirements:
        id: \d+

imie_skills_project_delete:
    path:    /project/delete/{id}
    defaults: { _controller: ImieSkillsBundle:Project:delete }
    requirements:
        id: \d+


# -------- STATE --------

imie_skills_state_index:
    path:    /state/index
    defaults: { _controller: ImieSkillsBundle:State:index }

imie_skills_state_add:
    path:    /state/add
    defaults: { _controller: ImieSkillsBundle:State:add }

imie_skills_state_modify:
    path:    /state/modify/{id}
    defaults: { _controller: ImieSkillsBundle:State:modify }
    requirements:
        id: \d+

imie_skills_state_delete:
    path:    /state/delete/{id}
    defaults: { _controller: ImieSkillsBundle:State:delete }
    requirements:
        id: \d+


# -------- SKILL --------

imie_skills_skill_index:
    path:    /skill/index
    defaults: { _controller: ImieSkillsBundle:Skill:index }

imie_skills_skill_add:
    path:    /skill/add
    defaults: { _controller: ImieSkillsBundle:Skill:add }

imie_skills_skill_modify:
    path:    /skill/modify/{id}
    defaults: { _controller: ImieSkillsBundle:Skill:modify }
    requirements:
        id: \d+

imie_skills_skill_delete:
    path:    /skill/delete/{id}
    defaults: { _controller: ImieSkillsBundle:Skill:delete }
    requirements:
        id: \d+


# -------- USER --------

imie_skills_user_index:
    path:    /user/index
    defaults: { _controller: ImieSkillsBundle:User:index }

imie_skills_user_details:
    path:    /user/{id}
    defaults: { _controller: ImieSkillsBundle:User:details }
    requirements:
      id: \d+

imie_skills_user_add:
    path:    /user/add
    defaults: { _controller: ImieSkillsBundle:User:add }

imie_skills_user_modify:
    path:    /user/modify/{id}
    defaults: { _controller: ImieSkillsBundle:User:modify }
    requirements:
        id: \d+

imie_skills_user_delete:
    path:    /user/delete/{id}
    defaults: { _controller: ImieSkillsBundle:User:delete }
    requirements:
        id: \d+


# -------- NOTIFICATION --------

imie_skills_notification_index:
    path:    /notification/index
    defaults: {_controller: ImieSkillsBundle:Notification:index }

imie_skills_notification_details:
    path:    /notification/{id}
    defaults: {_controller: ImieSkillsBundle:Notification:details }

imie_skills_notification_add:
    path:    /notification/add
    defaults: {_controller: ImieSkillsBundle:Notification:add }

imie_skills_notification_delete:
    path:    /notification/delete/{id}
    defaults : {_controller: ImieSkillsBundle:Notification:delete }
    requirements:
        id: \d+


# -------- MISC. --------

imie_skills_panel:
    path:    /panel
    defaults: { _controller: ImieSkillsBundle:Panel:index }

imie_skills_search:
    path:    /search
    defaults: { _controller: ImieSkillsBundle:Search:index }

imie_skills_contact:
    path:    /contact
    defaults: { _controller: ImieSkillsBundle:Contact:index }


# -------- FOSUser --------

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
