imie_skills_home:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Home:index }


# -------- FORMATION --------

imie_skills_school_add: 
    path:    /school/add
    defaults : {_controller: ImieSkillsBundle:School:add }

imie_skills_school_delete:
    path:    /school/delete
    defaults : {_controller: ImieSkillsBundle:School:delete }

imie_skills_course_add:
    path:    /course/add
    defaults : {_controller: ImieSkillsBundle:Course:add }

imie_skills_course_delete:
    path:    /course/delete
    defaults : {_controller: ImieSkillsBundle:Course:delete }

imie_skills_promo_add:
    path:    /promo/add
    defaults : {_controller: ImieSkillsBundle:Promo:add }

imie_skills_promo_delete:
    path:    /course/delete
    defaults : {_controller: ImieSkillsBundle:Promo:delete }


# -------- USER --------
imie_skills_users:
    path:     /users
    defaults: { _controller: ImieSkillsBundle:User:index }

imie_skills_user_me:
    path:     /user
    defaults: { _controller: ImieSkillsBundle:User:details }
    requirements:
      id: \d+

imie_skills_user_modify:
    path:     /user/modify/{id}
    defaults: { _controller: ImieSkillsBundle:User:modify }
    requirements:
        id: \d+

imie_skills_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: ImieSkillsBundle:User:delete }
    requirements:
        id: \d+

imie_skills_user_add:
    path:     /user/add
    defaults: { _controller: ImieSkillsBundle:User:add }


# -------- SKILL --------

imie_skills_skills:
    path:     /skills
    defaults: { _controller: ImieSkillsBundle:Skill:index }

imie_skills_skill_add:
    path:     /skill/add
    defaults: { _controller: ImieSkillsBundle:Skill:add }
    
imie_skills_skill_modify:
    path:     /skill/modify/{id}
    defaults: { _controller: ImieSkillsBundle:Skill:modify }
    requirements:
        id: \d+

imie_skills_skill_delete:
    path:     /skill/delete/{id}
    defaults: { _controller: ImieSkillsBundle:Skill:delete }
    requirements:
        id: \d+


# -------- PROJECT --------

imie_skills_project_details:
    path:     /project/{id}
    defaults: { _controller: ImieSkillsBundle:Project:details }
    requirements:
      id: \d+

imie_skills_project_delete:
    path:     /project/delete/{id}
    defaults: { _controller: ImieSkillsBundle:Project:delete }
    requirements:
      id: \d+

imie_skills_project_modify:
    path:     /project/modify/{id}
    defaults: { _controller: ImieSkillsBundle:Project:modify }
    requirements:
      id: \d+

imie_skills_project_index:
    path:     /projects
    defaults: { _controller: ImieSkillsBundle:Project:index }

imie_skills_project_add:
    path:     /project/add
    defaults: { _controller: ImieSkillsBundle:Project:add }


# -------- NOTIFICATION --------

imie_skills_notification_index:
    path:   /admin/notification
    defaults: {_controller: ImieSkillsBundle:Notification:index }

imie_skills_notification_details:
    path:   /notification/details
    defaults: {_controller: ImieSkillsBundle:Notification:details }

imie_skills_notification_add:
    path:   /notification/add
    defaults: {_controller: ImieSkillsBundle:Notification:add }

imie_skills_notification_delete:
    path:    /notification/delete/{id}
    defaults : {_controller: ImieSkillsBundle:Notification:remove }
    requirements:
        id: \d+
        
#-------------- SCHOOL---------------

imie_skills_school_add:
    path:    /school/add
    defaults : {_controller: ImieSkillsBundle:School:addSchool}

imie_skills_school_delete:
    path:    /school/delete
    defaults : {_controller: ImieSkillsBundle:School:deleteSchool}

imie_skills_course_add:
    path:    /course/add
    defaults : {_controller: ImieSkillsBundle:Course:addCourse}

imie_skills_course_delete:
    path:    /course/delete
    defaults : {_controller: ImieSkillsBundle:Course:deleteCourse}


# -------- MISC. --------

imie_skills_contact:
    path:     /contact
    defaults: { _controller: ImieSkillsBundle:Contact:index }

imie_skills_search:
    path:     /search
    defaults: { _controller: ImieSkillsBundle:Search:index }
# --------------SECURITY -------------------
imie_skills_login: 
    pattern:   /login
    defaults:  { _controller: ImieSkillsBundle:Security:login }
imie_skills_login_check:
    pattern:   /login_check
    
imie_skills_logout:
    pattern:   /logout
