imie_skills_home:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Home:index }

imie_skills_user_my_profile:
    path:     /user/{id}
    defaults: { _controller: ImieSkillsBundle:User:myProfile }
    requirements:
      id: \d+

imie_skills_user_add:
    path:     /user/add
    defaults: { _controller: ImieSkillsBundle:User:addUser }

imie_skills_skill_add:
    path:     /skill/add
    defaults: { _controller: ImieSkillsBundle:Skill:addSkill }

imie_skills_project_detail_projects:
    path:     /project/{id}
    defaults: { _controller: ImieSkillsBundle:Project:detailProjects }
    requirements:
      id: \d+

imie_skills_project_add_project:
    path:     /project/add
    defaults: { _controller: ImieSkillsBundle:Project:addProject }

imie_skills_project_index:
    path:     /projects
    defaults: { _controller: ImieSkillsBundle:Project:index }

imie_skills_contact:
    path:     /contact
    defaults: { _controller: ImieSkillsBundle:Contact:index }

imie_skills_search:
    path:     /search
    defaults: { _controller: ImieSkillsBundle:Search:newSearch }

imie_skills_homepage:
    path:     /
    defaults: { _controller: ImieSkillsBundle:Notification:index }

imie_notification_index:
    path:   /notification
    defaults: {_controller: ImieSkillsBundle:Notification:index}

imie_notification_add:
    path:   /notification/add
    defaults: {_controller: ImieSkillsBundle:Notification:add}

imie_notification_details:
    path:   /notification/details
    defaults: {_controller: ImieSkillsBundle:Notification:details}

imie_notification_delete:
    path:    /notification/delete
    defaults : {_controller: ImieSkillsBundle:Notification:delete}
